# this is currently not working

services:

  llm:
    image: gcr.io/mineonlium/partyllm@sha256:db7199747fcada2222277113a388b2f5eeee41e140510eb9426d3ec018e40be8
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=
    volumes:
      - ./vectorstore.pkl:/app/vectorstore.pkl